apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
  labels:
    app: gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
        - name: gateway
          image: 496278789073.dkr.ecr.ap-northeast-2.amazonaws.com/user10-gateway:latest
          ports:
            - containerPort: 8080