server:
  port: 8088

---

spring:
  profiles: default
  cloud:
    gateway:
      routes:
        - id: booking
          uri: http://localhost:8081
          predicates:
            - Path=/bookings/** 
        - id: confirm
          uri: http://localhost:8082
          predicates:
            - Path=/confirms/** 
        - id: notification
          uri: http://localhost:8083
          predicates:
            - Path=/notifications/** 
        - id: user
          uri: http://localhost:8084
          predicates:
            - Path=/users/**, /userLists/**
        - id: room
          uri: http://localhost:8085
          predicates:
            - Path=/rooms/** 
        - id: point
          uri: http://localhost:8086
          predicates:
            - Path=/points/** 
        - id: pointList
          uri: http://localhost:8087
          predicates:
            - Path= /pointLists/**
        - id: bookingList
          uri: http://localhost:8089
          predicates:
            - Path= /bookingLists/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true


---

spring:
  profiles: docker
  cloud:
    gateway:
      routes:
        - id: booking
          uri: http://booking:8080
          predicates:
            - Path=/bookings/** 
        - id: confirm
          uri: http://confirm:8080
          predicates:
            - Path=/confirms/** 
        - id: notification
          uri: http://notification:8080
          predicates:
            - Path=/notifications/** 
        - id: user
          uri: http://user:8080
          predicates:
            - Path=/users/**, /userLists/**
        - id: room
          uri: http://room:8080
          predicates:
            - Path=/rooms/** 
        - id: point
          uri: http://point:8080
          predicates:
            - Path=/points/** 
        - id: pointList
          uri: http://pointView:8080
          predicates:
            - Path= /pointLists/**
        - id: bookingList
          uri: http://bookingView:8080
          predicates:
            - Path= /bookingLists/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true

server:
  port: 8080
